# Generated by Django 4.2.5 on 2023-09-29 08:10

import Parking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_code', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenship_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Parking.models.upload_kyc_picture)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, default='Parking', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='Kathmandu', max_length=255, null=True)),
                ('car_slot', models.IntegerField(blank=True, null=True)),
                ('bike_slot', models.IntegerField(blank=True, null=True)),
                ('car_charge', models.IntegerField(blank=True, null=True)),
                ('bike_charge', models.IntegerField(blank=True, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('full_time', models.BooleanField(blank=True, default=False, null=True)),
                ('parking_type', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Parking.models.upload_parking_picture)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
