# Generated by Django 4.2.5 on 2023-09-29 09:11

import Customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_code', models.CharField(blank=True, max_length=255, null=True)),
                ('user_code', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_code', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(default='dibas', max_length=50)),
                ('bookedSeat', models.CharField(default='', max_length=10)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=0)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=Customer.models.upload_qr)),
                ('fine', models.IntegerField(blank=True, null=True)),
                ('departureTime', models.TimeField(default='00:00:00')),
                ('arrivalTime', models.TimeField(default='00:00:00')),
                ('departureDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicleID', models.CharField(max_length=50)),
                ('booked_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
